# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78cf834ff1e7d6e2c7b1ae5f40c615473bc6611117bbb73aec59262a42aa3d37031449e304e11576e8e48f714933497d243e61e8936bc49fc7b332147b6c5f7c

test:
  secret_key_base: f385557da12218e0064278e691e07257075d5146a31efeb0a769f96f38f69554b43f2497c4af1cd66ed5e125da38c47a2b81f960ae1c9b3661b8fd5ca8dffe08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
